version: '3'

volumes:
  mysql_storage:
    driver: 'local'

services:
  mysql:
    image: mysql:5.6
    volumes:
      - mysql_storage:/var/lib/mysql
    ports:
      - "3336:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
